@hostname = http://localhost:7047

# Token JWT finto e hardcodato, generato da jwt.io
# Questo token contiene i claim finti (sub, email, ecc.)
@localToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYmVlNTRiOC01NjY5LTQ1ZDQtOGE2Yy0yMzg1NWYyNWI4OTEiLCJuYW1lIjoiSm9obiBEb2UiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJqb2huLmRvZUBkZWFkLnV3IiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.pnL8qXbbiTQoUsL2nlr-w497UD__xvi0-8XxDPVjGLM

###
### Get My Profile - STANDARD JWT
GET {{hostname}}/api/profiles/me
Authorization: Bearer {{localToken}}

###

### Create or Update Profile - POST request (Local Testing)
POST {{hostname}}/api/profiles
Authorization: Bearer {{localToken}}
Content-Type: application/json

{
  "username": "TestUser",
  "bio": "Questa è la mia biografia di test"
}

###